name: Docker CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Builds Docker image
        run: docker build -t abhijitrayarao/shojo_anime:latest .
      - name: pushes to DockerHub
        run: |
          echo "${{ secrets.DOCKER_KEY }}" | docker login -u abhijitrayarao --password-stdin
          docker tag abhijitrayarao/shojo_anime:latest abhijitrayarao/shojo_anime:latest
          docker push abhijitrayarao/shojo_anime:latest
